# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sorcery"
  s.version = "0.8.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Noam Ben Ari"]
  s.date = "2013-11-10"
  s.description = "Provides common authentication needs such as signing in/out, activating by email and resetting password."
  s.email = "nbenari@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "lib/generators/sorcery/USAGE",
    "lib/generators/sorcery/install_generator.rb",
    "lib/generators/sorcery/templates/initializer.rb",
    "lib/generators/sorcery/templates/migration/activity_logging.rb",
    "lib/generators/sorcery/templates/migration/brute_force_protection.rb",
    "lib/generators/sorcery/templates/migration/core.rb",
    "lib/generators/sorcery/templates/migration/external.rb",
    "lib/generators/sorcery/templates/migration/remember_me.rb",
    "lib/generators/sorcery/templates/migration/reset_password.rb",
    "lib/generators/sorcery/templates/migration/user_activation.rb",
    "lib/sorcery.rb",
    "lib/sorcery/controller.rb",
    "lib/sorcery/controller/submodules/activity_logging.rb",
    "lib/sorcery/controller/submodules/brute_force_protection.rb",
    "lib/sorcery/controller/submodules/external.rb",
    "lib/sorcery/controller/submodules/external/protocols/certs/ca-bundle.crt",
    "lib/sorcery/controller/submodules/external/protocols/oauth1.rb",
    "lib/sorcery/controller/submodules/external/protocols/oauth2.rb",
    "lib/sorcery/controller/submodules/external/providers/base.rb",
    "lib/sorcery/controller/submodules/external/providers/facebook.rb",
    "lib/sorcery/controller/submodules/external/providers/github.rb",
    "lib/sorcery/controller/submodules/external/providers/google.rb",
    "lib/sorcery/controller/submodules/external/providers/linkedin.rb",
    "lib/sorcery/controller/submodules/external/providers/liveid.rb",
    "lib/sorcery/controller/submodules/external/providers/twitter.rb",
    "lib/sorcery/controller/submodules/external/providers/vk.rb",
    "lib/sorcery/controller/submodules/external/providers/xing.rb",
    "lib/sorcery/controller/submodules/http_basic_auth.rb",
    "lib/sorcery/controller/submodules/remember_me.rb",
    "lib/sorcery/controller/submodules/session_timeout.rb",
    "lib/sorcery/crypto_providers/aes256.rb",
    "lib/sorcery/crypto_providers/bcrypt.rb",
    "lib/sorcery/crypto_providers/common.rb",
    "lib/sorcery/crypto_providers/md5.rb",
    "lib/sorcery/crypto_providers/sha1.rb",
    "lib/sorcery/crypto_providers/sha256.rb",
    "lib/sorcery/crypto_providers/sha512.rb",
    "lib/sorcery/engine.rb",
    "lib/sorcery/model.rb",
    "lib/sorcery/model/adapters/active_record.rb",
    "lib/sorcery/model/adapters/mongo_mapper.rb",
    "lib/sorcery/model/adapters/mongoid.rb",
    "lib/sorcery/model/submodules/activity_logging.rb",
    "lib/sorcery/model/submodules/brute_force_protection.rb",
    "lib/sorcery/model/submodules/external.rb",
    "lib/sorcery/model/submodules/remember_me.rb",
    "lib/sorcery/model/submodules/reset_password.rb",
    "lib/sorcery/model/submodules/user_activation.rb",
    "lib/sorcery/model/temporary_token.rb",
    "lib/sorcery/railties/tasks.rake",
    "lib/sorcery/test_helpers.rb",
    "lib/sorcery/test_helpers/internal.rb",
    "lib/sorcery/test_helpers/internal/rails.rb",
    "lib/sorcery/test_helpers/rails.rb",
    "sorcery.gemspec",
    "spec/shared_examples/controller_oauth2_shared_examples.rb",
    "spec/shared_examples/controller_oauth_shared_examples.rb",
    "spec/shared_examples/user_activation_shared_examples.rb",
    "spec/shared_examples/user_activity_logging_shared_examples.rb",
    "spec/shared_examples/user_brute_force_protection_shared_examples.rb",
    "spec/shared_examples/user_oauth_shared_examples.rb",
    "spec/shared_examples/user_remember_me_shared_examples.rb",
    "spec/shared_examples/user_reset_password_shared_examples.rb",
    "spec/shared_examples/user_shared_examples.rb",
    "spec/sorcery_crypto_providers_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/NoamB/sorcery"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Magical authentication for Rails 3 applications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth>, ["~> 0.4.4"])
      s.add_runtime_dependency(%q<oauth2>, ["~> 0.8.0"])
      s.add_runtime_dependency(%q<bcrypt-ruby>, ["~> 3.0.0"])
      s.add_development_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_development_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<json>, [">= 1.7.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.5.0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0.3.8"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<mongo_mapper>, [">= 0"])
      s.add_development_dependency(%q<mongoid>, ["~> 2.4.4"])
    else
      s.add_dependency(%q<oauth>, ["~> 0.4.4"])
      s.add_dependency(%q<oauth2>, ["~> 0.8.0"])
      s.add_dependency(%q<bcrypt-ruby>, ["~> 3.0.0"])
      s.add_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<json>, [">= 1.7.7"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.5.0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0.3.8"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<mongo_mapper>, [">= 0"])
      s.add_dependency(%q<mongoid>, ["~> 2.4.4"])
    end
  else
    s.add_dependency(%q<oauth>, ["~> 0.4.4"])
    s.add_dependency(%q<oauth2>, ["~> 0.8.0"])
    s.add_dependency(%q<bcrypt-ruby>, ["~> 3.0.0"])
    s.add_dependency(%q<abstract>, [">= 1.0.0"])
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<json>, [">= 1.7.7"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.5.0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0.3.8"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<mongo_mapper>, [">= 0"])
    s.add_dependency(%q<mongoid>, ["~> 2.4.4"])
  end
end

