require 'rake'
require 'rspec/core/rake_task'

desc 'Default: Run all specs.'
task :default => :spec

desc "Run all specs"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec_modular/*_spec.rb'
  t.rspec_opts = ["--options #{File.dirname(__FILE__)}/spec_modular/spec.opts"]
end