source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "simple_auth", '0.1.0', :path => '../../../'

group :development do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'ruby-debug19'
end
