source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "sorcery", '0.1.1', :path => '../../../'
gem 'bcrypt-ruby', '~> 2.1.4', :require => 'bcrypt'
  
group :development do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'ruby-debug19'
  gem 'simplecov', '>= 0.3.8', :require => false # Will install simplecov-html as a dependency
end
