source 'http://rubygems.org'

gem 'sinatra', '>= 1.2.0'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem "sorcery", '0.4.0', :path => '../../'

group :development, :test do
  gem "rspec", "~> 2.5.0"
  gem 'ruby-debug19'
  gem 'simplecov', '>= 0.3.8', :require => false # Will install simplecov-html as a dependency
  gem 'timecop'
end
