source 'http://rubygems.org'

gem "rails", '3.0.3'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem "sorcery", '0.1.1', :path => '../../../'

group :development do
  gem 'rspec'
  gem 'ruby-debug19'
  gem 'simplecov', '>= 0.3.8', :require => false # Will install simplecov-html as a dependency
end
